In [1]:
import ROOT, rat
import os, sys
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline 
import rat

TClass::TClass:0: RuntimeWarning: no dictionary for class omtext is available


In [29]:
infile_name = '/project/6001358/jpyanez/rat-scripts/cherenkov_mc/output2.root'

In [30]:
try:
    ratreader.close()
    print 'Closing file before reopenning'
except:
    print 'No ratreader file. Opening it for the first time'
ratreader = rat.dsreader(infile_name)

Closing file before reopenning


In [31]:
# Get one DS, run entry from the file
ds, run = ratreader.next()

In [32]:
# Get the MC info for this DS entry (event)
mymc = ds.GetMC()

In [33]:
# How many tracks inside (all particle segments)
print mymc.GetMCTrackCount()

2209


In [39]:
# Take one track inside and follow its steps
# The first will be the primary electron. There might be some secondaries produced.
itrack = 1
mytrack = mymc.GetMCTrack(itrack)
print 'PDG code:', mytrack.GetPDGCode()


PDG code: 11


In [35]:
for istep in range(mytrack.GetMCTrackStepCount()):
    mystep = mytrack.GetMCTrackStep(istep)
    position = np.array(mystep.GetPosition())
    momentum = np.array(mystep.GetMomentum())
    end_volume = mystep.GetEndVolume()
    process = mystep.GetProcess()
    
    print 'Step ', istep
    print position, momentum
    print end_volume, process

Step  0
[0. 0. 0.] [0.       0.       5.487257]
world Unknown
Step  1
[-0.00019233  0.00068997  0.05109172] [-0.0326052   0.03447779  5.48109484]
world Cerenkov
Step  2
[0.00049609 0.00150614 0.10218542] [0.00940304 0.09968461 5.43278313]
world Cerenkov
Step  3
[0.00027036 0.00360612 0.1532578 ] [-0.64546084  0.04581095  5.39049101]
world Cerenkov
Step  4
[-0.00564997  0.00324121  0.20402159] [-0.77972502  0.11178559  5.35617256]
world Cerenkov
Step  5
[-0.01351458  0.00460931  0.25450352] [-0.75307506  0.12936682  5.35069561]
world Cerenkov
Step  6
[-0.02064668  0.00503599  0.30511531] [-0.74639553  0.14600056  5.34660196]
world Cerenkov
Step  7
[-0.02894462  0.00640601  0.35554224] [-0.7089026   0.07101742  5.34748936]
world Cerenkov
Step  8
[-0.03574483  0.00639433  0.40620193] [-0.61408669 -0.06747025  5.35174131]
world Cerenkov
Step  9
[-0.04263602  0.00525391  0.4568471 ] [-0.65788424 -0.09320451  5.34065151]
world Cerenkov
Step  10
[-0.04874301  0.00335926  0.50756776] [-0.43614

[-0.99409032  0.64866638  7.75693321] [-0.21155557  0.00688833  4.26776934]
world Cerenkov
Step  155
[-0.99814886  0.64869761  7.80822086] [-0.27010581  0.04457557  4.25677109]
world Cerenkov
Step  156
[-1.00027418  0.6498068   7.8596096 ] [-0.16314223  0.14682743  4.25638914]
world Cerenkov
Step  157
[-1.00159144  0.6515196   7.91099834] [-0.18314511  0.05957027  4.25163555]
world Cerenkov
Step  158
[-1.00231111  0.65193748  7.96244717] [-0.18301719  0.17036442  4.23856783]
world Cerenkov
Step  159
[-1.0037601   0.65478349  8.01379585] [-0.1476474   0.19353558  4.23434782]
world Cerenkov
Step  160
[-1.00475228  0.65668613  8.06519794] [-0.17516698  0.13457298  4.22994566]
world Cerenkov
Step  161
[-1.00675213  0.6569168   8.11661911] [-2.29097024e-01  8.30579374e-04  4.22231770e+00]
world Cerenkov
Step  162
[-1.00909173  0.65540332  8.16801167] [-0.12534909 -0.04303477  4.22030735]
world Cerenkov
Step  163
[-1.01189148  0.65435219  8.21938992] [-0.13569546  0.04603264  4.21366215]
wor

[-1.31130779  0.05704581 16.83895493] [-0.6008957  -0.43124175  2.76886654]
world Cerenkov
Step  333
[-1.32172525  0.04992419 16.88991737] [-0.49968585 -0.41826421  2.78545761]
world Cerenkov
Step  334
[-1.3302381   0.03997527 16.94081497] [-0.50694978 -0.45926782  2.77146912]
world Cerenkov
Step  335
[-1.34051669  0.03355498 16.9919548 ] [-0.45624858 -0.30640391  2.79499769]
world Cerenkov
Step  336
[-1.34892356  0.02570582 17.04324532] [-0.30589864 -0.42513424  2.7825098 ]
world Cerenkov
Step  337
[-1.35558271  0.01955338 17.09503937] [-0.2699275  -0.25226057  2.79848599]
world Cerenkov
Step  338
[-1.35967994e+00  1.62458457e-02  1.71473560e+01] [-0.40324453 -0.32515177  2.77018356]
world Cerenkov
Step  339
[-1.36685550e+00  7.92870298e-03  1.71988068e+01] [-0.42280313 -0.44519612  2.74519992]
world Cerenkov
Step  340
[-1.37416923e+00 -6.14883538e-05  1.72502518e+01] [-0.32189    -0.51261401  2.72612953]
world Cerenkov
Step  341
[-1.38049150e+00 -1.12681696e-02  1.73012791e+01] [-0.1

[-3.62881088 -5.02072668 23.20309258] [-0.48103109 -0.65066308  1.26998556]
world Cerenkov
Step  501
[-3.65231586 -5.04435921 23.25116158] [-0.53388232 -0.63651663  1.24441683]
world Cerenkov
Step  502
[-3.67427492 -5.0645051  23.30162048] [-0.50069708 -0.58346492  1.27500772]
world Cerenkov
Step  503
[-3.69347882 -5.08368587 23.34248352] [-0.82894468 -0.39231095  0.9755888 ]
world eIoni
Step  504
[-3.72901487 -5.10267496 23.38795662] [-0.87760419 -0.33537683  0.93952006]
world Cerenkov
Step  505
[-3.77262521 -5.11494255 23.42894173] [-0.92993319 -0.18423979  0.89657444]
world Cerenkov
Step  506
[-3.82015014 -5.12350893 23.46716499] [-0.91305786 -0.13136829  0.90763062]
world Cerenkov
Step  507
[-3.8682754  -5.12924528 23.50569725] [-0.95455408  0.01075065  0.80188364]
world Cerenkov
Step  508
[-3.91798067 -5.13369036 23.54393387] [-0.93174344  0.07032467  0.80981809]
world Cerenkov
Step  509
[-3.9626894  -5.12505484 23.58772278] [-0.91887176  0.25201169  0.77292699]
world Cerenkov
Ste

In [40]:
# Take one track inside and follow its steps
# The code 0 are optical photons. The scattering length is really long.
# Usually one, two steps will take you to the surface I made
itrack = 5
mytrack = mymc.GetMCTrack(itrack)
print 'PDG code:', mytrack.GetPDGCode()

PDG code: 0


In [41]:
for istep in range(mytrack.GetMCTrackStepCount()):
    mystep = mytrack.GetMCTrackStep(istep)
    position = np.array(mystep.GetPosition())
    momentum = np.array(mystep.GetMomentum())
    end_volume = mystep.GetEndVolume()
    process = mystep.GetProcess()
    
    print 'Step ', istep
    print position, momentum
    print end_volume, process

Step  0
[-9.84552025e-05  3.53198149e-04  2.61541810e-02] [2.07557832e-06 2.99428763e-07 2.36306369e-06]
world Cerenkov
Step  1
[3941.71801758  568.64367676 4487.70605469] [2.07557832e-06 2.99428763e-07 2.36306369e-06]
dark_sphere Transportation
