In [1]:
import ROOT, rat
import os, sys, pickle

import matplotlib.pyplot as plt
import numpy as np
import collections
%matplotlib inline 

import jp_mpl as jplot
import geo_studies, rat_misc

from scipy import optimize
reload(rat_misc)
from matplotlib.colors import LogNorm
import pickle

# My tools
import jp_analysis as analysis


TClass::TClass:0: RuntimeWarning: no dictionary for class omtext is available


In [2]:
# Airplane mode
db = rat.RAT.DB.Get()
db.SetAirplaneModeStatus(True)
db.SetDefaultPlaneLockStatus(False)
print 'This is AIRPLANE MODE - be careful!'

This is AIRPLANE MODE - be careful!


TClass::TClass:0: RuntimeWarning: no dictionary for class RAT::DBTableKey is available


In [94]:
pmt_info = pickle.load(open('/home/jpyanez/snoplus/snoplus_python/pmt_positions.pckl'))


In [98]:
infile_name = '/home/jpyanez/snoplus/data/october17_data_test/Analysis_r0000104887_s003_p000.root'

In [113]:
reader = rat.dsreader(infile_name)

In [114]:
pmts_in_file = []

In [115]:
aux.GetCount()

0L

In [116]:
for ds, run in reader:
    for iev in range(ds.GetEVCount()):
        event = ds.GetEV(iev)
        pmts = event.GetCalPMTs()
        for one_pmt in range(pmts.GetAllCount()):
            this_pmt = pmts.GetAllPMT(one_pmt)
            pmts_in_file.append(this_pmt.GetID())


In [117]:
print len(pmts_in_file)

2881964


In [118]:
pmts_in_file = np.unique(pmts_in_file)

In [119]:
len(pmts_in_file)

9191

In [120]:
pmts_in_file.sort()

In [121]:
for one_pmt in pmts_in_file:
    if pmt_info['type'][one_pmt] != 1:
        print 'Found a different PMT'
        print one_pmt
        print pmt_info['type'][one_pmt]
        print pmt_info['xyz'][one_pmt]

Found a different PMT
0
10.0
[-99999. -99999. -99999.]
Found a different PMT
153
10.0
[-99999. -99999. -99999.]
Found a different PMT
200
10.0
[-99999. -99999. -99999.]
Found a different PMT
513
3.0
[-99999. -99999. -99999.]
Found a different PMT
1022
10.0
[-99999. -99999. -99999.]
Found a different PMT
1026
3.0
[-99999. -99999. -99999.]
Found a different PMT
1229
10.0
[-99999. -99999. -99999.]
Found a different PMT
1230
10.0
[-99999. -99999. -99999.]
Found a different PMT
1233
10.0
[-99999. -99999. -99999.]
Found a different PMT
1538
3.0
[-99999. -99999. -99999.]
Found a different PMT
2016
2.0
[-2032.  2098. -8729.]
Found a different PMT
2017
2.0
[ 5151.  2196. -7301.]
Found a different PMT
2018
2.0
[-3964.  4708. -6840.]
Found a different PMT
2019
2.0
[ 3253.  5225. -6840.]
Found a different PMT
2020
2.0
[ -497.  5577. -7301.]
Found a different PMT
2021
2.0
[ 1367.  2581. -8729.]
Found a different PMT
2022
2.0
[-6942.  3693. -4785.]
Found a different PMT
2023
2.0
[-5187.  6332. -4258

In [47]:
for one_pmt in pmts_in_file:
    if pmt_info['type'][one_pmt] != 1:
        print 'Found a different PMT'
        print one_pmt
        print pmt_info['type'][one_pmt]
        print pmt_info['xyz'][one_pmt]

Found a different PMT
2515
7.0
[ 1050.26  7415.17  3846.69]
Found a different PMT
3536
7.0
[-4287.58  6152.61  3796.11]
Found a different PMT
3856
7.0
[-6600.28  3114.85  4197.48]
Found a different PMT
8163
7.0
[ 2545.4  -7078.81  3737.76]


In [45]:
pmt_info.keys()

['xyz', 'type', 'phi', 'costheta']

In [97]:
np.sum(pmt_info['type']==7)

4