In [1]:
import rat, ROOT
import os, sys
%pylab inline
import jp_mpl as jplot

Populating the interactive namespace from numpy and matplotlib


TClass::TClass:0: RuntimeWarning: no dictionary for class omtext is available


In [2]:
data = rat.socreader('/home/jpyanez/snoplus/data/SOC_files_reflections/SOC_0000102529.root')

In [3]:
mc = rat.socreader('/home/jpyanez/rundir/laserball/337/0_0_0/2_lb_wn_337_p0_p0_p0.root')

In [4]:
socdata, run = data.next()

In [5]:
socmc, runmc = mc.next()

In [13]:
np.array(socdata.calib.GetPos())

array([   0., -254.,   25.])

In [14]:
np.array(socmc.calib.GetPos())

array([ 0.,  0.,  0.])

In [16]:
np.array(socdata.GetFitResult(socdata.GetFitNames()[0]).GetVertex(0).GetPosition())


array([ -10.89273453, -216.66325378,   32.9556427 ])

In [17]:
np.array(socmc.GetFitResult(socmc.GetFitNames()[0]).GetVertex(0).GetPosition())


IndexError: index out of range

In [20]:
len(socdata.GetFitNames())

1