## Testing Aksel's "native" geometry<br> Photon bomb at 380nm & 500 nm<br> Using labppo only<br>Moved from photons from a single point to photons from a ball of 10cm radius

In [1]:
import ROOT, rat
import os, sys
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline  
sys.path.append('/home/jp/projects/snoplus/snoing/install/rat-dev/example/pyroot')
sys.path.append('/home/jp/projects/python_tools')
sys.path.append('/home/jp/projects/snoplus/python_modules')
import jp_mpl as jplot
import lowlevel_stats
reload(lowlevel_stats)
import snoplots
reload(snoplots)

TClass::TClass:0: RuntimeWarning: no dictionary for class omtext is available
TClass::TClass:0: RuntimeWarning: no dictionary for class RAT::DU::ShadowingCalculator is available


<module 'snoplots' from '/home/jp/projects/snoplus/python_modules/snoplots.pyc'>

In [2]:
outdir = '/home/jp/Dropbox/workflowy/snoplus/nativegeo_validation/photon_ball_1016'

In [3]:
# Initialize the data dictionary
data = {}

In [4]:
basedir = '/home/jp/projects/snoplus/rundir/nativegeo_finalcheck'

### Using photon bomb ball (the hits are distributed over a sphere)

#### Scintillator comparisons

In [5]:
lowlevel_stats.readFile(data, basedir, 'native','pbomb380.root', 'native380')

In [6]:
lowlevel_stats.readFile(data, basedir, 'snoplus','pbomb380.root', 'snoplus380')

In [18]:
def compareHits(data = None, datasets  = []):
    nhits = np.zeros([len(datasets), 4], dtype=float)
    for i, one_set in enumerate(datasets):
        nhits[i,:] = np.sum(data[one_set]['nhit'], axis=0)
    
    # Now let's normalize to the official geometry
    nhits_relerror = np.sqrt(nhits)/nhits
    
    nhits_normed = nhits/nhits[0,3]
    nhits_error  = nhits_normed*nhits_relerror
    
    print nhits_normed
    print nhits_error
    print nhits_normed[0,:]/nhits_normed[1,:]


In [19]:
compareHits(data, ['snoplus380', 'native380'])

[[ 0.41840043  0.14388003  0.43771954  1.        ]
 [ 0.42893812  0.13888138  0.4316401   0.99945961]]
[[ 0.00751833  0.00440885  0.00768995  0.01162319]
 [ 0.00761242  0.00433159  0.00763636  0.01162005]]
[ 0.97543307  1.03599222  1.01408451  1.00054069]


In [14]:
lowlevel_stats.readFile(data, basedir, 'native','pbomb500.root', 'native500')

In [13]:
lowlevel_stats.readFile(data, basedir, 'snoplus','pbomb500.root', 'snoplus500')

In [20]:
compareHits(data, ['snoplus500', 'native500'])

[[ 0.41772336  0.13948404  0.4427926   1.        ]
 [ 0.41918088  0.13321673  0.42136715  0.97376476]]
[[ 0.0078028   0.00450888  0.00803353  0.01207275]
 [ 0.0078164   0.00440642  0.00783676  0.01191333]]
[ 0.99652295  1.04704595  1.05084746  1.02694207]
