In [1]:
import os, sys
sys.path.append('/home/jp/projects/icecube/oscFit_trunk_martin/modules')
import pickle, dataLoader
import numpy as np
reload(dataLoader)

<module 'dataLoader' from '/home/jp/projects/icecube/oscFit_trunk_martin/modules/dataLoader.pyc'>

In [2]:
loader =  dataLoader.dataLoader(observables = 
                                ['reco_energy', 'reco_zenith', 'reco_energy'],
                                bin_edges   =    
                                [10**np.linspace(0.8,1.75,9),
                                 np.arccos(np.linspace(-1,0.,9))[::-1],
                                 [0, np.inf]],
                                user = 'quickstart', 
                                LEaxis = [],      
                                weight_keys = ['weight_e', 'weight_mu'],
                                verbose = False)


 ************************************ 
 **** oscFitND v1.1 - dataLoader ****
 ************************************

dataLoader: Initializing user quickstart
dataLoader: MC loaded successfully!
dataLoader: Muon background templates loaded successfully!
dataLoader: Loading systematic variations using default values.


In [3]:
loader.numu['50']['CC']['weight']

array([  9.78e-10,   4.00e-10,   3.70e-09, ...,   2.73e-10,   6.92e-10,   6.86e-10])

In [4]:
loader.atmmu_unweighted

{'corsika': array([[[ 0.],
         [ 0.],
         [ 0.],
         [ 0.],
         [ 0.],
         [ 0.],
         [ 0.],
         [ 0.]],
 
        [[ 0.],
         [ 0.],
         [ 0.],
         [ 0.],
         [ 0.],
         [ 0.],
         [ 0.],
         [ 0.]],
 
        [[ 0.],
         [ 0.],
         [ 0.],
         [ 0.],
         [ 0.],
         [ 0.],
         [ 0.],
         [ 0.]],
 
        [[ 0.],
         [ 0.],
         [ 0.],
         [ 0.],
         [ 0.],
         [ 0.],
         [ 0.],
         [ 0.]],
 
        [[ 0.],
         [ 0.],
         [ 0.],
         [ 0.],
         [ 0.],
         [ 0.],
         [ 0.],
         [ 0.]],
 
        [[ 0.],
         [ 0.],
         [ 0.],
         [ 0.],
         [ 0.],
         [ 0.],
         [ 0.],
         [ 0.]],
 
        [[ 0.],
         [ 0.],
         [ 0.],
         [ 0.],
         [ 0.],
         [ 0.],
         [ 0.],
         [ 0.]],
 
        [[ 0.],
         [ 0.],
         [ 0.],
         [ 0.],
        

In [5]:
a = raw_input()

damn


In [6]:
a

'damn'

In [27]:
energy = np.array([1,2,3,1,2,3,1,3])
eaxis = np.linspace(1,3,5)

In [36]:
a, b = np.histogramdd([energy for x in range(3)], [eaxis, np.array([-np.inf, np.inf]),np.array([-np.inf, np.inf])])

In [29]:
a

array([[[ 3.]],

       [[ 0.]],

       [[ 2.]],

       [[ 3.]]])

In [30]:
b

[array([ 1. ,  1.5,  2. ,  2.5,  3. ]),
 array([-inf,  inf]),
 array([-inf,  inf])]